name: Greetings

on: issues

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for raising issue, I will get back to you"
        pr-message: "Thanks for raising issue, I will get back to you"
